# Parsing
LOCAL_DATA_PATH: ../data/data.txt
HEADER_LOCAL_DATA_PATH: ../data/data.header
LOG_FILE_PATH: log/deduper_log.txt
SEPARATOR: "\t"

# Deduper
DEDUPER_FIELDS:  # Those fields will be used in the model
# Type can be one of 'String' or 'Exact'.  Fields defined as String will be compared using difflib.SequenceMatcher while fields defined as Exact will be compared on whether or not they have an identical value
- name: NameFirst
  type: String
- name: NameLast
  type: String
- name: EMailAddress
  type: Exact
- name: PhoneNumber
  type: String
DEDUPER_GROUND_TRUTH_FIELD: PersonID

# Model
TEST_RELATIVE_SIZE: 0.3
RANDOM_SEED: 42 # Set to None for a truly random seed
PREDICATE_FUNCTIONS:
- base_key: NameFirst
  predicate_type: FirstChars
  predicate_value: 3
MIN_TRUE_MATCHES_FOR_EVALUATION: 20